# Generated by Django 3.0.3 on 2020-02-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_hero_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
