# Generated by Django 3.0.3 on 2020-02-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20200211_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='author',
            field=models.CharField(default='zcx', max_length=5),
        ),
    ]
