# Generated by Django 3.0.3 on 2020-02-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0007_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='tags', to='booktest.Article'),
        ),
    ]
